/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * main.c
 * Author: NIVYA
 * Description: Simple UART command parser to turn an LED on D8 (PA9) ON or OFF.
 */

#include <string.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"
#include "stm32f446xx_usart_driver.h"

USART_Handle_t usart2_handle;

void USART2_GPIOInit(void)
{
    GPIO_Handle_t usart_gpios = {0};
    usart_gpios.pGPIOx = GPIOA;
    usart_gpios.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    usart_gpios.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    usart_gpios.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
    usart_gpios.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
    usart_gpios.GPIO_PinConfig.GPIO_PinAltFunMode = 7;

    // Configure PA2 (TX) and PA3 (RX)
    usart_gpios.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_2;
    GPIO_Init(&usart_gpios);
    usart_gpios.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;
    GPIO_Init(&usart_gpios);
}

void LED_D8_GPIOInit(void)
{
    GPIO_Handle_t GpioLed = {0};
    GpioLed.pGPIOx = GPIOA;
    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9; // D8 maps to PA9
    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_Init(&GpioLed);
}

void USART2_Init(void)
{
    usart2_handle.pUSARTx = USART2;
    usart2_handle.USART_Config.USART_Baud = USART_STD_BAUD_115200;
    usart2_handle.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;
    usart2_handle.USART_Config.USART_Mode = USART_MODE_TXRX;
    usart2_handle.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
    usart2_handle.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
    usart2_handle.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
    USART_Init(&usart2_handle);
}

int main(void)
{
    char command_buffer[8] = {0};
    uint8_t idx = 0;

    LED_D8_GPIOInit();
    USART2_GPIOInit();
    USART2_Init();
    USART_PeripheralControl(USART2, ENABLE);

    uint8_t greeting[] = "Type 'ON' or 'OFF':\r\n";
    USART_SendData(&usart2_handle, greeting, sizeof(greeting) - 1);

    while(1)
    {
        // 1. Wait for character
        while(!USART_GetFlagStatus(USART2, USART_FLAG_RXNE));
        char rx_byte = (char)(USART2->DR & 0xFF);

        // 2. Echo character back to terminal
        USART_SendData(&usart2_handle, (uint8_t*)&rx_byte, 1);

        // 3. Handle Enter key to process command
        if(rx_byte == '\r' || rx_byte == '\n')
        {
            if(idx > 0)
            {
                command_buffer[idx] = '\0'; // Null-terminate

                // 4. Check commands
                if(strcmp(command_buffer, "ON") == 0)
                {
                    GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_9, 1);
                    USART_SendData(&usart2_handle, (uint8_t*)"\r\nLED IS ON\r\n", 13);
                }
                else if(strcmp(command_buffer, "OFF") == 0)
                {
                    GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_9, 0);
                    USART_SendData(&usart2_handle, (uint8_t*)"\r\nLED IS OFF\r\n", 14);
                }
                else
                {
                    USART_SendData(&usart2_handle, (uint8_t*)"\r\nUNKNOWN\r\n", 11);
                }

                idx = 0; // Reset buffer index
            }
        }
        // 5. Ignore incoming newline debris, store normal text characters
        else if(rx_byte != '\0')
        {
            if(idx < sizeof(command_buffer) - 1)
            {
                command_buffer[idx++] = rx_byte;
            }
        }
    }
    return 0;
}

