/**
 ******************************************************************************
 * @file : main.c
 * @author : Auto-generated by STM32CubeIDE
 * @brief : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"



int main(void)
{


 void delay_5ms(void)
 {
 for (volatile uint32_t i = 0; i < 840000; i++);
 }




 GPIOA_CLK_EN() ; // clock gpio enable

 GPIOA->MODER &= ~(0x3 << 10); // make 10 11 posisiton zero

 GPIOA->MODER |= (1<<10); //- 01 → General-purpose outputmode to pin 11 and 10

 GPIOA->OTYPER &= ~(1<<5); //- Clearing bit 5 makes pin 5 push-pull (standard LED drive).

 GPIOA ->OSPEEDR &= ~(0x3 << 10);
 GPIOA->OSPEEDR |= (1<<10); // - 01 → Medium speed


 GPIOA ->PUPDR &= ~(0x3 << 10); // - 00 → No pull-up/pull-down

 //GPIOA->ODR &=~(1<<5); // pin 5 is OFF by setting 5 bit
 //GPIOA->ODR |=(1<<5); // pin 5 is ON state
 /* Loop forever */


 while (1)
 {
 GPIOA->ODR ^= (1 << 5); // toggle LED
 delay_5ms(); // wait ~2 seconds
 }


}
