

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "tm1637.h"
#include <stdio.h>

int main(void)
{
    TM1637_Init();

    uint8_t hour = 10;
    uint8_t min  = 30;

    printf("TM1637 Smartwatch started\r\n");

    while (1)
    {
        TM1637_DisplayTime(hour, min);

        // PRINT to SWV ITM console
        printf("Time: %02d:%02d\r\n", hour, min);

        // delay
        for (volatile uint32_t i = 0; i < 800000; i++);

        min++;
        if (min == 60)
        {
            min = 0;
            hour++;
        }
        if (hour == 24)
        {
            hour = 0;
        }
    }
}
